name: ci

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: install dependencies
        run: pip install -r requirment.txt

      - name: check python syntax
        run: python -m py_compile extract.py

      - name: Build docker image
        run: docker build -t my-etl .

      - name: run container docker
        run: docker run --rm my-etl

      - name: login docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: tag docker image
        run: docker tag my-etl areeb1w/my-etl:latest

      - name: push docker image
        run: docker push areeb1w/my-etl:latest

  cd:
    needs: ci
    runs-on: self-hosted

    steps:
      - name: Deploy ETL on Ubuntu
        run: |
          docker pull areeb1w/my-etl:latest
          docker stop my-etl-container || true
          docker rm my-etl-container || true
          docker run -d --name my-etl-container areeb1w/my-etl:latest
